io.write("Digite numero inteiro menor que 32: ")
numero = tonumber(io.read())
d1 = math.floor(numero % 2)
resto1 = math.floor(numero / 2)
d2 = math.floor(resto1 % 2)
resto2 = math.floor(resto1 / 2)
d3 = math.floor(resto2 % 2)
resto3 = math.floor(resto2 / 2)
d4 = math.floor (resto3 % 2)
resto4 = math.floor(resto3 / 2)
d5 = math.floor(resto4 % 2)

print("Este numero em binario é:")
print(d5..d4..d3..d2..d1)
