io.write("Digite sua idade em Dias:")
dias = tonumber(io.read())
anos = math.floor(Dias / 365)
meses = math.floor(Dias / 30)
dias_sobra = math.floor(Dias % 30) 
print("Sua idade em anos é:  "..(Anos).."   Anos")
print("sua idade em meses: "..(Meses).."  Meses".."  e "..(dias_sobra).."  dias!" )
